# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Deploy CodeSheep

on:
  push:
    branches: [ "master" ]


env:
  SERVER_PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
  SERVER_USER: ${{ secrets.USERNAME }}
  SERVER_HOST: ${{ secrets.HOST }}}
    

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x, 14.x, 16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm run build --if-present
    
    - name: Deploy
      uses: easingthemes/ssh-deploy@v2.2.11
      with:
          SSH_PRIVATE_KEY: ${{ SERVER_PRIVATE_KEY }}
          REMOTE_HOST: ${{ SERVER_HOST }}
          REMOTE_USER: ${{ SERVER_HOST }}
          SOURCE: 'build/'
          TARGET: '/var/www/html/codesheep'
          ARGS: '-avz --delete'
    
    
    
    
    
