# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Deploy CodeSheep

on:
  push:
    branches: [ "master" ]


env:
  CI: false
    

jobs:
  build:

    runs-on: ubuntu-latest


    steps:
    - uses: actions/checkout@v3
    
    - name: Use Node.js 
      uses: actions/setup-node@v3
      with:
        node-version: 16.16.0

    - name: Cache
      uses: actions/cache@v3.0.7
      env:
          cache-name: cache-node-modules
      with:
          path: ./node_modules
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('./package.json') }} 
          restore-keys: |
              ${{ runner.os }}-build-${{ env.cache-name }}-
              ${{ runner.os }}-build-
              ${{ runner.os }}-

      
    - name: install
      run: npm i
    - name: build
      run: npm run build
    
    - name: Deploy
      uses: easingthemes/ssh-deploy@v2.2.11
      with:
          SSH_PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
          REMOTE_HOST: ${{ secrets.HOST }}
          REMOTE_USER: ${{ secrets.USERNAME }}
          SOURCE: 'build/'
          TARGET: '/var/www/html/codesheep'
          ARGS: '-avz --delete'
    
    
    
    
    
